//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP_VENDOR_CREATE_SERVICE
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SAP_VENDOR_CREATE_SERVICE.ztest")]
    public interface ztest
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ztest:ZMM_RFC_VENDOR_CREATERequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATEResponse1> ZMM_RFC_VENDOR_CREATEAsync(SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATERequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_RFC_VENDOR_CREATE
    {
        
        private ZMM_ST_VENDOR_DATA[] iM_VENDOR_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMM_ST_VENDOR_DATA[] IM_VENDOR_DATA
        {
            get
            {
                return this.iM_VENDOR_DATAField;
            }
            set
            {
                this.iM_VENDOR_DATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_ST_VENDOR_DATA
    {
        
        private string cOMPANY_CODEField;
        
        private string pURCHASING_ORGField;
        
        private string aCCOUNT_GRPField;
        
        private string nAME1Field;
        
        private string nAME2Field;
        
        private string nAME3Field;
        
        private string sEARCH_TERMField;
        
        private string sTREET_2Field;
        
        private string sTREET_3Field;
        
        private string sTREET_HOUSE_NUMBERField;
        
        private string sTREET_4Field;
        
        private string sTREET_5Field;
        
        private string cITYField;
        
        private string pOSTAL_CODEField;
        
        private string dISTRICTField;
        
        private string cOUNTRYField;
        
        private string rEGIONField;
        
        private string lANGUAGEField;
        
        private string tELEPHONEField;
        
        private string tEL_EXTENSField;
        
        private string fAXField;
        
        private string mOBILE_PHONEField;
        
        private string e_MAILField;
        
        private string tAX_NUMBER_3Field;
        
        private string iNDUSTRYField;
        
        private string iNITIATORS_NAMEField;
        
        private string pAN_NUMBERField;
        
        private string gST_VEN_CLASSField;
        
        private string fIRST_NAMEField;
        
        private string cP_NAMEField;
        
        private string rECON_ACCOUNTField;
        
        private string oRDER_CURRENCYField;
        
        private string iNCOTERMSField;
        
        private string iNCOTERMS_TEXTField;
        
        private string sCHEMA_GROUP_VENDORField;
        
        private string gR_BASED_INV_VERIFField;
        
        private string sRV_BASED_INV_VERIFField;
        
        private string vENDOR_CODEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string COMPANY_CODE
        {
            get
            {
                return this.cOMPANY_CODEField;
            }
            set
            {
                this.cOMPANY_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PURCHASING_ORG
        {
            get
            {
                return this.pURCHASING_ORGField;
            }
            set
            {
                this.pURCHASING_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ACCOUNT_GRP
        {
            get
            {
                return this.aCCOUNT_GRPField;
            }
            set
            {
                this.aCCOUNT_GRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NAME1
        {
            get
            {
                return this.nAME1Field;
            }
            set
            {
                this.nAME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NAME2
        {
            get
            {
                return this.nAME2Field;
            }
            set
            {
                this.nAME2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NAME3
        {
            get
            {
                return this.nAME3Field;
            }
            set
            {
                this.nAME3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SEARCH_TERM
        {
            get
            {
                return this.sEARCH_TERMField;
            }
            set
            {
                this.sEARCH_TERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string STREET_2
        {
            get
            {
                return this.sTREET_2Field;
            }
            set
            {
                this.sTREET_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string STREET_3
        {
            get
            {
                return this.sTREET_3Field;
            }
            set
            {
                this.sTREET_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string STREET_HOUSE_NUMBER
        {
            get
            {
                return this.sTREET_HOUSE_NUMBERField;
            }
            set
            {
                this.sTREET_HOUSE_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string STREET_4
        {
            get
            {
                return this.sTREET_4Field;
            }
            set
            {
                this.sTREET_4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string STREET_5
        {
            get
            {
                return this.sTREET_5Field;
            }
            set
            {
                this.sTREET_5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CITY
        {
            get
            {
                return this.cITYField;
            }
            set
            {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string POSTAL_CODE
        {
            get
            {
                return this.pOSTAL_CODEField;
            }
            set
            {
                this.pOSTAL_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string DISTRICT
        {
            get
            {
                return this.dISTRICTField;
            }
            set
            {
                this.dISTRICTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string COUNTRY
        {
            get
            {
                return this.cOUNTRYField;
            }
            set
            {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string REGION
        {
            get
            {
                return this.rEGIONField;
            }
            set
            {
                this.rEGIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string LANGUAGE
        {
            get
            {
                return this.lANGUAGEField;
            }
            set
            {
                this.lANGUAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string TELEPHONE
        {
            get
            {
                return this.tELEPHONEField;
            }
            set
            {
                this.tELEPHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string TEL_EXTENS
        {
            get
            {
                return this.tEL_EXTENSField;
            }
            set
            {
                this.tEL_EXTENSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string FAX
        {
            get
            {
                return this.fAXField;
            }
            set
            {
                this.fAXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string MOBILE_PHONE
        {
            get
            {
                return this.mOBILE_PHONEField;
            }
            set
            {
                this.mOBILE_PHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string E_MAIL
        {
            get
            {
                return this.e_MAILField;
            }
            set
            {
                this.e_MAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string TAX_NUMBER_3
        {
            get
            {
                return this.tAX_NUMBER_3Field;
            }
            set
            {
                this.tAX_NUMBER_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string INDUSTRY
        {
            get
            {
                return this.iNDUSTRYField;
            }
            set
            {
                this.iNDUSTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string INITIATORS_NAME
        {
            get
            {
                return this.iNITIATORS_NAMEField;
            }
            set
            {
                this.iNITIATORS_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string PAN_NUMBER
        {
            get
            {
                return this.pAN_NUMBERField;
            }
            set
            {
                this.pAN_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string GST_VEN_CLASS
        {
            get
            {
                return this.gST_VEN_CLASSField;
            }
            set
            {
                this.gST_VEN_CLASSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string FIRST_NAME
        {
            get
            {
                return this.fIRST_NAMEField;
            }
            set
            {
                this.fIRST_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string CP_NAME
        {
            get
            {
                return this.cP_NAMEField;
            }
            set
            {
                this.cP_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string RECON_ACCOUNT
        {
            get
            {
                return this.rECON_ACCOUNTField;
            }
            set
            {
                this.rECON_ACCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string ORDER_CURRENCY
        {
            get
            {
                return this.oRDER_CURRENCYField;
            }
            set
            {
                this.oRDER_CURRENCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string INCOTERMS
        {
            get
            {
                return this.iNCOTERMSField;
            }
            set
            {
                this.iNCOTERMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string INCOTERMS_TEXT
        {
            get
            {
                return this.iNCOTERMS_TEXTField;
            }
            set
            {
                this.iNCOTERMS_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string SCHEMA_GROUP_VENDOR
        {
            get
            {
                return this.sCHEMA_GROUP_VENDORField;
            }
            set
            {
                this.sCHEMA_GROUP_VENDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string GR_BASED_INV_VERIF
        {
            get
            {
                return this.gR_BASED_INV_VERIFField;
            }
            set
            {
                this.gR_BASED_INV_VERIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string SRV_BASED_INV_VERIF
        {
            get
            {
                return this.sRV_BASED_INV_VERIFField;
            }
            set
            {
                this.sRV_BASED_INV_VERIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string VENDOR_CODE
        {
            get
            {
                return this.vENDOR_CODEField;
            }
            set
            {
                this.vENDOR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMM_RFC_VENDOR_CREATEResponse
    {
        
        private ZMM_ST_VENDOR_DATA[] eX_VENDOR_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMM_ST_VENDOR_DATA[] EX_VENDOR_DATA
        {
            get
            {
                return this.eX_VENDOR_DATAField;
            }
            set
            {
                this.eX_VENDOR_DATAField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMM_RFC_VENDOR_CREATERequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATE ZMM_RFC_VENDOR_CREATE;
        
        public ZMM_RFC_VENDOR_CREATERequest()
        {
        }
        
        public ZMM_RFC_VENDOR_CREATERequest(SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATE ZMM_RFC_VENDOR_CREATE)
        {
            this.ZMM_RFC_VENDOR_CREATE = ZMM_RFC_VENDOR_CREATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZMM_RFC_VENDOR_CREATEResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATEResponse ZMM_RFC_VENDOR_CREATEResponse;
        
        public ZMM_RFC_VENDOR_CREATEResponse1()
        {
        }
        
        public ZMM_RFC_VENDOR_CREATEResponse1(SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATEResponse ZMM_RFC_VENDOR_CREATEResponse)
        {
            this.ZMM_RFC_VENDOR_CREATEResponse = ZMM_RFC_VENDOR_CREATEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ztestChannel : SAP_VENDOR_CREATE_SERVICE.ztest, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ztestClient : System.ServiceModel.ClientBase<SAP_VENDOR_CREATE_SERVICE.ztest>, SAP_VENDOR_CREATE_SERVICE.ztest
    {
        
        public ztestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATEResponse1> SAP_VENDOR_CREATE_SERVICE.ztest.ZMM_RFC_VENDOR_CREATEAsync(SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATERequest request)
        {
            return base.Channel.ZMM_RFC_VENDOR_CREATEAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATEResponse1> ZMM_RFC_VENDOR_CREATEAsync(SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATE ZMM_RFC_VENDOR_CREATE)
        {
            SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATERequest inValue = new SAP_VENDOR_CREATE_SERVICE.ZMM_RFC_VENDOR_CREATERequest();
            inValue.ZMM_RFC_VENDOR_CREATE = ZMM_RFC_VENDOR_CREATE;
            return ((SAP_VENDOR_CREATE_SERVICE.ztest)(this)).ZMM_RFC_VENDOR_CREATEAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
